### ISSUE TITLE
Enum in schema should create NS_ENUM

### ISSUE THREAD

**Issue by sethfri** [cknadler/nidyx#33]
Using an enum in a schema should generate an NS_ENUM in the model

**Comment by cknadler** [comment]
I've looked into this in the past. JSONModel doesn't support serializing to this, so I doubt support can be added. If you figure out a way, please reopen.

**Comment by sethfri** [comment]
In that case, how do you feel about adding some `extern NSString *`s to the header file so that consumers of the model can check the value of the property?

**Comment by cknadler** [comment]
Sure, that's a great idea. Feel free to open an issue for it.
